#!/usr/bin/env python3
import base64
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "shared"))

from demo_assets import (  # noqa: E402
    DEMO_ASSET_DIR,
    discover_demo_source,
    demo_data_path,
    demo_manifest_path,
)


MIME_TYPES = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
}


def main():
    try:
        source = discover_demo_source(ROOT)
    except ValueError as error:
        raise SystemExit(str(error)) from error

    output = demo_data_path(ROOT)
    manifest = demo_manifest_path(ROOT)
    data = base64.b64encode(source.read_bytes()).decode("ascii")
    mime_type = MIME_TYPES[source.suffix.lower()]
    relative_source = source.relative_to(ROOT).as_posix()
    relative_output = output.relative_to(ROOT).as_posix()
    relative_manifest = manifest.relative_to(ROOT).as_posix()

    output.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text(
        "(function (app) {\n"
        "    // Generated by tools/generate-demo-data/run.py.\n"
        f"    // Demo source: {relative_source}\n"
        "    app.assets = app.assets || {};\n"
        "    app.assets.demoImage = "
        + json.dumps(
            {
                "fileName": source.name,
                "url": relative_source,
                "dataScript": relative_output,
            },
            separators=(",", ":"),
        )
        + ";\n"
        "})(window.DitherApp);\n",
        encoding="utf-8",
    )
    output.write_text(
        "(function (app) {\n"
        "    // Generated by tools/generate-demo-data/run.py.\n"
        f"    // Demo source: {relative_source}\n"
        "    // Server/GitHub Pages loads the source image directly and does not need this file.\n"
        "    // Direct file:// opening needs this fallback to avoid canvas taint.\n"
        f"    // When replacing the demo image in {DEMO_ASSET_DIR.as_posix()}, run: python3 tools/generate-demo-data/run.py\n"
        "    app.assets = app.assets || {};\n"
        "    app.assets.demoImageData = "
        + json.dumps(
            {
                "fileName": source.name,
                "dataUrl": f"data:{mime_type};base64,{data}",
            },
            separators=(",", ":"),
        )
        + ";\n"
        "})(window.DitherApp);\n",
        encoding="utf-8",
    )
    print(f"Wrote {relative_manifest}")
    print(f"Wrote {relative_output} from {relative_source}")


if __name__ == "__main__":
    main()
